### DISCUSSION TITLE
Dinamically creating backend's state file and selecting state file during runtime

### DISCUSSION THREAD

**Discussion by BrenonOrtega** [opentofu/opentofu#1590] [Q&A] [answered]
Hey, I want to ask how you guys handle multiple types of environment regarding terraform backend.

Im writing a pipeline using github actions that can deploy multiple different dev/uat/prod environments using a given unique name (e.g: dev-my-env1, prod-disaster-recovey, uat-automation-tests).

I want to be able to use this dinamic names to name my resources and split vpcs, internet gateways, subnets, ecs task definitions and etc, this would mean that each environment could have its own state.

The problem is I can run terraform init passing the backend config on the CLI parameters, but I have not found a way to select which state file to point during the workflow run to run the plan and apply later.

What I was expecting was something like this:

`
 # Initialization steps above 

      - name: Initialize tofu
        working-directory: infrastructure/
        run: |
          tofu init -backend-config="bucket=${{ env.tf_state_bucket }}" \
            -backend-config="key=${{ inputs.environment_type }}-${{ inputs.environment_name }}-terraform.tfstate" \
            -backend-config="region=${{ inputs.region }}" 

      - name: Plan changes
        working-directory: infrastructure/
        run: |
          tofu plan -backend-config="bucket=${{ env.tf_state_bucket }}" \
            -backend-config="key=${{ env.full_name }}-terraform.tfstate" \
            -backend-config="region=${{ inputs.region }}" \
            -var-file="./variables/default.tfvars" \
            -var-file="./variables/${{ inputs.environment_type }}-variables.tfvars"
`

**Comment by flightlesstux** [comment, marked as answer]
hi @BrenonOrtega,

as you showed in your example, you initialize Terraform with environment-specific backend configuration during the terraform init step. Ensure that this configuration is consistent across init, plan, and apply steps for the same environment. This is crucial to avoid inconsistencies and potential state corruption.

here’s a refined example that sticks to best practices:

```
jobs:
  tofu_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup OpenTofu
        # Ensure you have a step to setup OpenTofu if there's any action or manual setup required

      - name: Tofu Initialize
        working-directory: infrastructure/
        run: |
          tofu init -backend-config="bucket=${{ env.tf_state_bucket }}" \
            -backend-config="key=${{ inputs.environment_type }}-${{ inputs.environment_name }}-tofu.tfstate" \
            -backend-config="region=${{ inputs.region }}"

      - name: Tofu Plan
        working-directory: infrastructure/
        run: |
          tofu plan -var-file="./variables/default.tfvars" \
            -var-file="./variables/${{ inputs.environment_type }}-variables.tfvars"

      - name: Tofu Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: infrastructure/
        run: |
          tofu apply
```

I hope, it'll help to you! 🙌🏻
