### DISCUSSION TITLE
"tofu fmt -check" not returning error codes when running in a github workflow?

### DISCUSSION THREAD

**Discussion by larsks** [opentofu/opentofu#2493] [Q&A] [answered]
I have a github workflow that runs `tofu fmt`:

```
on:
  pull_request:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: opentofu/setup-opentofu@v1
      - uses: actions/checkout@v4
      - run: tofu fmt -recursive -check -diff
```

I made a test commit that is missing a quote, and the jobs runs *successfully*, despite reporting the error:

```
╷
│ Error: Invalid multi-line string
│ 
│   on versions.tf line 4, in terraform:
│    4:       source  = "integrations/github
│    5:       version = "~> 6.0"
│ 
│ Quoted strings may not be split over multiple lines. To produce a
│ multi-line string, either use the \n escape to represent a newline
│ character or use the "heredoc" multi-line template syntax.
╵
.
.
.
```

When I run `tofu fmt -recursive -check -diff` on my local machine, it returns an error code as expected:

```
$ tofu fmt -recursive -check -diff
╷
│ Error: Invalid multi-line string
│ 
│   on versions.tf line 4, in terraform:
│    4:       source  = "integrations/github
│    5:       version = "~> 6.0"
│ 
│ Quoted strings may not be split over multiple lines. To produce a
│ multi-line string, either use the \n escape to represent a newline
│ character or use the "heredoc" multi-line template syntax.
╵
.
.
.

$ echo $?
2
```

What's going on here? The version of opentofu running in the workflow matches what I'm running locally (1.9.0).
