### ISSUE TITLE
Use yaml for variable instead of hcl

### ISSUE THREAD

**Issue by littlejo** [opentofu/opentofu#1500]
### OpenTofu Version

```shell
Latest
```

### Use Cases

If you need complex input such as object(...), yaml is more easy to read than hcl format (too verbose for me)
So I propose to have ability to use yaml file for variable.

### Attempted Solutions

yamldecode function is a workaround.

### Proposal

```
var:
  - name: region
    type: string
    default: us-east-1
```

Could be overrided by:
```
tofu.yaml:
region: eu-west-3
```
