### ISSUE TITLE
OpenTofu Incorrectly Prefaces Heredoc Statements with a YAML Block Scalar Indicator

### ISSUE THREAD

**Issue by JHansen2000** [opentofu/opentofu#1910]
### OpenTofu Version

```shell
OpenTofu v1.8.1
on linux_amd64
+ provider registry.opentofu.org/lxc/incus v0.1.2
```

### OpenTofu Configuration Files

```hcl
resource "incus_profile" "test-profile" {
  name = "test-profile"

  config = {
    "boot.autostart" = true
    "linux.kernel_modules" = "ip_vs,ip_vs_rr,ip_vs_wrr,ip_vs_sh,ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,br_netfilter"
    "raw.lxc" = <<EOT
lxc.apparmor.profile = unconfined
lxc.mount.auto = proc:rw sys:rw cgroup:rw
lxc.cgroup.devices.allow = a
lxc.cap.drop =
EOT
    "security.nesting" = true
    "security.privileged" = true
  }
}
```

### Debug Output

Omitted, can provide some information if needed.

### Expected Behavior

`tofu apply` should result in the following incus deployment:
```yaml
config:
  boot.autostart: "true"
  linux.kernel_modules: ip_vs,ip_vs_rr,ip_vs_wrr,ip_vs_sh,ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,br_netfilter
  raw.lxc:
    lxc.apparmor.profile = unconfined
    lxc.mount.auto = proc:rw sys:rw cgroup:rw
    lxc.cgroup.devices.allow = a
    lxc.cap.drop =
  security.nesting: "true"
  security.privileged: "true"
description: ""
name: test-profile
used_by: []
project: default
```

### Actual Behavior

`tofu apply` results in the following incus deployment:
```yaml
config:
  boot.autostart: "true"
  linux.kernel_modules: ip_vs,ip_vs_rr,ip_vs_wrr,ip_vs_sh,ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,br_netfilter
  raw.lxc: | # <-- This YAML Block Scalar Indicator causes failure
    lxc.apparmor.profile = unconfined
    lxc.mount.auto = proc:rw sys:rw cgroup:rw
    lxc.cgroup.devices.allow = a
    lxc.cap.drop =
  security.nesting: "true"
  security.privileged: "true"
description: ""
name: test-profile
used_by: []
project: default
```

### Steps to Reproduce

`tofu init`
`tofu apply`

See: 
```yaml
# incus_profile.test-profile will be created
  + resource "incus_profile" "test-profile" {
      + config = {
          + "boot.autostart"       = "true"
          + "linux.kernel_modules" = "ip_vs,ip_vs_rr,ip_vs_wrr,ip_vs_sh,ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,br_netfilter"
          + "raw.lxc"              = <<-EOT
                lxc.apparmor.profile = unconfined
                lxc.mount.auto = proc:rw sys:rw cgroup:rw
                lxc.cgroup.devices.allow = a
                lxc.cap.drop =
            EOT
          + "security.nesting"     = "true"
          + "security.privileged"  = "true"
        }
      + name   = "test-profile"
    }
```

### Additional Context

https://opentofucommunity.slack.com/archives/C05R0FD0VRU/p1723057466684739
