### ISSUE TITLE
Dockerimage update base image

### ISSUE THREAD

**Issue by ProbstDJakob** [opentofu/opentofu#1931]
### OpenTofu Version

```shell
irrelevant
```

### Use Cases

We use the docker image in our CI/CD environment and need to install additional dependencies. The dependencies are available in later versions of alpine but not in 3.18, thus we need to add the repositories of a later version which could lead to problems.

### Attempted Solutions

Use repositories from later versions.

### Proposal

If there are no reasons to stick to a specific alpine version, it would be nice if either `latest` (points to the latest stable version, not to edge) or `3` would be used.

**Comment by ProbstDJakob** [comment]
No, we use it directly in the GitLab pipeline as follows:

```yaml
some-job:
  stage: deploy
  image:
    name: ghcr.io/opentofu/opentofu:1
    entrypoint: [ "" ]
  before_script:
    - apk add some-dependency-only-available-from-3.20-onwards
  script:
    - tofu apply
```
