### ISSUE TITLE
Opentofu with Azure not working in Github Actions

### ISSUE THREAD

**Issue by bbaabemhp** [opentofu/opentofu#1937]
### OpenTofu Version

```shell
1.7.1
```

### OpenTofu Configuration Files

not relevant

### Debug Output

Error: Error building ARM Config: please ensure you have installed Azure CLI version 2.0.79 or newer. Error parsing json result from the Azure CLI: launching Azure CLI: exec: "az": executable file not found in $PATH.

### Expected Behavior

Logging in

### Actual Behavior

Error within github actions

### Steps to Reproduce

```yaml
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TF_VAR_environment: stg
  ARM_CLIENT_ID: ""
  ARM_SUBSCRIPTION_ID: ""
  ARM_TENANT_ID: ""

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: stg-self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runner's shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runner's shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: "Login and do something"
        uses: azure/CLI@v1
        with:
          azcliversion: 2.61.0
          inlineScript: |
            az login --identity
            az group list
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.7.1
          
      - name: "Hi"
        working-directory: ./deployment/new_infra
        run: tofu init

      - id: plan
        working-directory: ./deployment/new_infra
        run: tofu plan -no-color
```
