### ISSUE TITLE
Cannot run "tofu console" in GitHub Actions workflow in non-interactive mode

### ISSUE THREAD

**Issue by thusfrancisco** [opentofu/opentofu#2282]
### OpenTofu Version

```shell
1.8.1
```

### OpenTofu Configuration Files

```yaml
name: Tofu Console

on: pull_request

jobs:
  tf-console:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Tofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.1

      - name: Run tofu console with piping
        id: tf-console
        run: |
          echo "Running console..."
          echo "[1, 1]" | tofu console
          echo "This never prints"
```

### Debug Output

Running console...

### Expected Behavior

Running console...
[
  1,
  1
]
This never prints

### Actual Behavior

Running console...

### Steps to Reproduce

Run the above GH action

### Additional Context

If you run locally

`echo "$SOME_HCL_CODE" | tofu console`

it should print out and close the console. Also works locally (and fails in GH actions) with "tofu console < command.txt", heredoc syntax, etc. Nothing seems to make it work in GH Actions.
