### ISSUE TITLE
Remove "Reading/Reading complete" messages for data sources from plan -concise

### ISSUE THREAD

**Issue by AurimasNav** [opentofu/opentofu#2409]
### OpenTofu Version

```shell
OpenTofu v1.9.0
on darwin_arm64
```

### The problem in your OpenTofu project

If the intent of `-concise` flag is to generate a plan for CI to add to the PR description for example, the output is still too verbose as it outputs all the data source "reading" and "read complete" actions. In some cases that results in overly noisy output, for one anecdote where I would expect it to only display:
`No changes. Your infrastructure matches the configuration.`
In addition it displays 122 lines of reading data source resources.

### Attempted Solutions

Parsing the output with additional tools.

### Proposal

Either hide reading/read complete messages for -concise by default or introduce another level of concise in case there are scenarios that current behavior would be preferable (can't think of one).

example of lines to remove from `plan -concise`

```yaml
data.azurerm_resource_group.connectivity: Reading...
data.azurerm_client_config.current: Reading...
data.azurerm_client_config.current: Read complete after 0s 
```
