### ISSUE TITLE
Request: Support for GitHub Action 

### ISSUE THREAD

**Issue by rdhar** [opentofu/opentofu#556]
### OpenTofu Version

```shell
>1.5, >1.6
```

### Use Cases

As a platforms IaC guy, I'm heavily reliant on the hashicorp/setup-terraform GitHub Action in order to provision TF via automation. Here's an [example in situ](https://github.com/devsectop/tf-via-pr/blob/2c8e32801123baae025f4fff2bbc1ae14c1c49e6/.github/workflows/tf.yml#L196).

Am I right to assume that an OpenTofu equivalent of that GitHub Action will be available from initial release? Just to make it super-accessible as a drop-in replacement at scale.

If so, more than happy to help validate preview releases across a extensive AWS IaC projects I work on.

### Attempted Solutions

Thanks to @zimeg (from [Slack](https://opentofucommunity.slack.com/archives/C05QF5HA0BH/p1695507933533049?thread_ts=1695420789.157869&cid=C05QF5HA0BH)), a serviceable workaround exists by downloading, installing and initializing the OpenTofu CLI in 3 steps (as per [BUILDING.md](https://github.com/opentofu/opentofu/blob/main/BUILDING.md) instructions).

```yaml
- name: Download the tofu source
  uses: actions/checkout@v4
  with:
    repository: opentofu/opentofu
    path: opentofu

- name: Install tofu tooling
  uses: actions/setup-go@v4
  with:
    go-version-file: opentofu/go.mod
    cache-dependency-path: opentofu/go.sum

- name: Prepare the tofu command
  working-directory: opentofu
  run: |
    go build -ldflags "-w -s -X 'github.com/opentofu/opentofu/version.dev=no'" -o bin/tofu .
    echo $(pwd)/bin >> $GITHUB_PATH
```

### Proposal

As of writing this, I can see that a proposed [opentofu/setup-opentofu](https://github.com/opentofu/setup-opentofu) already work-in-progress. I'll keep an eye on releases for the repo and support any testing endeavour.

There is also a relevant discussion in #411 started by @John-Donalson.

### References

While this is in direct reference to the hashicorp/setup-terraform GitHub Action, I'm hesitant to directly link to it as it's not an OpenTofu project (even though it is _currently_ MPL-2.0 licensed).
